name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_webrtc:
    git:
      url: git@github.com:turingvideo/flutter-webrtc.git
      ref: 54ef6d5e63152261c037cf8bc0ed08147a788e16
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2
  after_layout: ^1.1.0
  rxdart: ^0.27.2
  orientation: ^1.3.0
  fijkplayer: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
